### ISSUE TITLE
patched apk and frida not working

### ISSUE THREAD

**Issue by keralaboy123** [Eltion/Instagram-SSL-Pinning-Bypass#1]
i tried both 2 menthods on my android phone redmi notr 4 android 7 nothing worked. it is not intercepting connections.please check before posting.

**Comment by Eltion** [comment]
@keralaboy123 thanks for the feedback. I did test the methods and they are working, at least for me 😊. 

Can you tell me which ABI are you trying? x86, x86_64, armeabi-v7a, arm64-v8a?
Which tool are you using to intercept the traffic?
Are you using an emulator or an android phone?

**Comment by keralaboy123** [comment]
it was a problem of proxy client i was used.now i tried another proxy client and its working.thanks
