### ISSUE TITLE
[BUG] dont work when second  open app with already logged in

### ISSUE THREAD

**Issue by xbyl1234** [Eltion/Instagram-SSL-Pinning-Bypass#12]
it look like than must connect mqtt.Facebook.com , but this link is socket .

**Comment by LPeng111** [comment]
me too

**Comment by Eltion** [comment]
Can you describe your problem in more details. Also please include what proxy tool you're using and script logs

**Comment by kingbotss** [comment]
It is working on first,: open app, login and other activities. Close app.

If we open second time, it is closing the app

**Comment by kingbotss** [comment]
> 

Mitm proxy

**Comment by Eltion** [comment]
@kingbotss  I just tested. It's working on my device. This is probably not an issue with SSL bypass. It would help me debug this if you could attach adb logcat, and follow the bug guide I've attached.

**Comment by TenUchikawa** [comment]
I am having the same problem with mitmproxy 8.1.1.
It worked fine with burpsuite.

Operating environment
ubuntu22.04


Anyway thanks for the great code.

**Comment by ghyath5** [comment]
I'm facing the same issue
I think it is not an ssl issue, I think the requests goes under wss protocol so that mitmproxy couldn't catch the requests

**Comment by ghyath5** [comment]
Same issue here!

**Comment by Eltion** [comment]
Seems like instagram started using HTTP3 which is why this is happening. 
You can follow for more info here:

https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/issues/19
