### ISSUE TITLE
Could you provide a Burp Suite usage demo?

### ISSUE THREAD

**Issue by vasilywang** [Eltion/Instagram-SSL-Pinning-Bypass#13]
How to use Burp Suite to sniffer Instagram api？

**Comment by Eltion** [comment]
I will soon add a wiki page explaining that.

**Comment by Eltion** [comment]
You can check the wiki here: https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/wiki/Capture-packets-using-Brup-Suite

**Comment by vasilywang** [comment]
Thank you so much! It's my
