### ISSUE TITLE
[BUG] Not proxied properly.

### ISSUE THREAD

**Issue by TenUchikawa** [Eltion/Instagram-SSL-Pinning-Bypass#16]
Everything was fine until yesterday, but today I can't do it.

I tried both frida and the patched APK, but I couldn't do both.

when I'm trying to login. long loading started and finally I got this error
![image](https://user-images.githubusercontent.com/63717580/196044307-9b63e294-e86c-45cc-b8ea-9a409b94d609.png)

**Comment by Eltion** [comment]
@TenUchikawa  it would be really helpful for me if you edit your original question following the bug template provided. That way I get all the necessary information to help you.
Here is the template: https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/issues/new?assignees=Eltion&labels=&template=bug_report.md&title=%5BBUG%5D

**Comment by Eltion** [comment]
Duplicate https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/issues/18
