### ISSUE TITLE
[BUG]sometimes can work but sometimes can't work

### ISSUE THREAD

**Issue by zhajingwen** [Eltion/Instagram-SSL-Pinning-Bypass#17]
**Describe the bug**  

**Method**  
Patched APK

**App info**
 - Version: instagram-v256.0.0.18.105-arm64-v8a.apk
 - Arch:  arm64-v8a

**Device info**
- Model: xiaomi 8
- Android Version: 8.1

**Proxy tool**
charles: v4.6.2

**Logs**
![0285a18f76f6affbe6043cf3933b4ee](https://user-images.githubusercontent.com/33952447/197133961-ec569586-1e9e-467f-9a0f-cdeba52b34d4.jpg)

**Additional context**
有时候能用有时候不能用，能用的时候是可以正常抓包的，不能用的时候手机APP什么数据都加载不进来，APP一片空白

**Comment by Eltion** [comment]
@zhajingwen, It would really be helpful if you could provide the logs form your proxy tool
