### ISSUE TITLE
[BUG] not proxied properly

### ISSUE THREAD

**Issue by TenUchikawa** [Eltion/Instagram-SSL-Pinning-Bypass#18]
**Describe the bug**  
Everything was fine until last week, for now I can't do it.
I tried both frida and the patched APK, but I couldn't do both.
when I'm trying to login. long loading started and finally I got "An unknown network error has occured" Error

**Method**  
Both APK and Frida

**App info**
 - BypassedApkVersion: instagram-v256.0.0.18.105
 - ApkVersionWhenUseFrida:instagram-v257.1.0.16.110
 - Arch: x86

**Device info**
- Model: Genymotion(10), docker-android(10), pixel5a(real device)(12)
- Android Version: 10,12

**Proxy tool**
mitmproxy: v8.1.1

**Logs**
[mitm-bypassed-apk.log](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/files/9844740/mitm-bypassed-apk.log)
[logcat-bypassed-apk.log](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/files/9844763/logcat-bypassed-apk.log)
[logcat-with-frida.log](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/files/9844765/logcat-with-frida.log)
[mitm-with-frida.log](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/files/9844766/mitm-with-frida.log)

**Additional context**
These logs comes from genymotion
please check.

**Comment by TenUchikawa** [comment]
I thought I commented on a previous Issue, but a new Issue was created. My apologies.

**Comment by Eltion** [comment]
@TenUchikawa  thanks for providing that information! I can see in the logs that it's the instagram API is returning `502 Bad Gateway 58b`, there is no problem with the SSL handshake so this error is probably not related to the SSL bypass.
I would suggest the following:
1. Try connecting to a VPN ( Do this on your pc, where you are running mitmproxy)
2. Test if normal instagram is working

**Comment by TenUchikawa** [comment]
Hi, thanks for answer.

I have changed proxy host to another ip address that ip working on normal instagram apk and also working when not enable proxy with pinning bypassed apk.
but I'm getting same result..

I'm curious why status code is 200 before press the login button




```
192.168.1.245:37844: POST https://b.i.instagram.com/api/v1/zr/tokens/ HTTP/2.0
         << HTTP/2.0 200 OK 190b
192.168.1.245:37844: POST https://b.i.instagram.com/api/v1/attribution/log_attribution/ HTTP/2.0
         << HTTP/2.0 200 OK 15b
192.168.1.245:37856: client connect
192.168.1.245:37844: POST https://b.i.instagram.com/api/v1/accounts/get_prefill_candidates/ HTTP/2.0
         << HTTP/2.0 200 OK 81b
192.168.1.245:37844: POST https://b.i.instagram.com/api/v1/accounts/contact_point_prefill/ HTTP/2.0
         << HTTP/2.0 200 OK 15b
192.168.1.245:37844: POST https://b.i.instagram.com/api/v1/launcher/mobileconfig/ HTTP/2.0
         << HTTP/2.0 200 OK 4.2k

-------------------------------------------------------Press login button-------------------------------------------------------

192.168.1.245:37862: client connect
192.168.1.245:37864: client connect
192.168.1.245:37866: client connect
192.168.1.245:37856: client disconnect
192.168.1.245:37856: error establishing server connection: client disconnected
192.168.1.245:37856: CONNECT graph.instagram.com:443
                  << 502 Bad Gateway 62b
192.168.1.245:37870: client connect
192.168.1.245:37862: client disconnect
192.168.1.245:37862: error establishing server connection: client disconnected
192.168.1.245:37862: CONNECT i.instagram.com:443
                  << 502 Bad Gateway 58b
192.168.1.245:37864: client disconnect
192.168.1.245:37864: error establishing server connection: client disconnected
192.168.1.245:37864: CONNECT i.instagram.com:443
                  << 502 Bad Gateway 58b
192.168.1.245:37872: client connect
192.168.1.245:37874: client connect
192.168.1.245:37876: client connect
192.168.1.245:37866: client disconnect
192.168.1.245:37866: error establishing server connection: client disconnected
192.168.1.245:37866: CONNECT i.instagram.com:443
                  << 502 Bad Gateway 58b
192.168.1.245:37878: client connect
192.168.1.245:37870: client disconnect
192.168.1.245:37870: error establishing server connection: client disconnected
192.168.1.245:37870: CONNECT graph.instagram.com:443
                  << 502 Bad Gateway 62b
192.168.1.245:37880: client connect
192.168.1.245:37872: client disconnect
192.168.1.245:37872: error establishing server connection: client disconnected
192.168.1.245:37872: CONNECT i.instagram.com:443
                  << 502 Bad Gateway 58b
192.168.1.245:37874: client disconnect
192.168.1.245:37874: error establishing server connection: client disconnected
192.168.1.245:37874: CONNECT i.instagram.com:443
                  << 502 Bad Gateway 58b
192.168.1.245:37876: client disconnect
192.168.1.245:37876: error establishing server connection: client disconnected
192.168.1.245:37876: CONNECT i.instagram.com:443
                  << 502 Bad Gateway 58b
192.168.1.245:37882: client connect
192.168.1.245:37884: client connect
192.168.1.245:37886: client connect
```
