### ISSUE TITLE
Failed to install on Android R+ (30+)

### ISSUE THREAD

**Issue by Eltion** [Eltion/Instagram-SSL-Pinning-Bypass#2]
Patched apk fails to install on Android R and above.

adb install output:

`adb: failed to install instagram-v239.0.0.14.111-x86.apk: Failure [-124: Failed parse during installPackageLI: Targeting R+ (version 30 and above) requires the resources.arsc of installed APKs to be stored uncompressed and aligned on a 4-byte boundary]`

**Comment by Eltion** [comment]
Fixed with 74e9bd23442732181b2bae73f47a46e6da56ec61. Removed compressing from resources.arsc

**Comment by michelerenzullo** [comment]
> Failure [-124: Failed parse during installPackageLI: Targeting R+ (version 30 and above) requires the resources.arsc of installed APKs to be stored uncompressed and aligned on a 4-byte boundary]

I think you are still compressing resources.arsc.
In the new Android sdk I changed zipalign **-p** -f 4 , please not the -p argument **is required now**. But for some reason it doesn't work still with your python script

It might be useful take a look at [my script](https://github.com/michelerenzullo/Workplace_SSL_Unpinning/tree/main/dev/tools) that I use everyday with IG etc... it copies the raw res files and compile/replace just the edited classes.dex, zipalign, sign and install. 
Edit "my_path" of your tools and "nome"(name) of your apk.
Note: I have those sub paths: apks(original apk), apks_d(decompiled by apktool) and apks_s(signed)

Run:
`aut.bat classes classes2`


```
set my_path=C:\Users\miki\Michele\APK

set nome=Instagram_237.0.0.14.102-363704332
rem set classes=classes4 classes3 classes2 etc... lista delle classi
set classes=%*

for %%a in (%classes%) do (if %%a==classes (java -Xmx3000m -jar %my_path%\smali-2.5.2.jar ass %my_path%\apks_d\%nome%\smali -o %my_path%\apks_d\%nome%\%%a.dex) else (java -Xmx3000m -jar %my_path%\smali-2.5.2.jar ass %my_path%\apks_d\%nome%\smali_%%a -o %my_path%\apks_d\%nome%\%%a.dex))

if not exist %my_path%\apks_s\NUL mkdir %my_path%\apks_s\

COPY "%my_path%\apks\%nome%.apk" "%my_path%\apks_s\toalign%nome%.apk" /Y

for %%a in (%classes%) do 7za.exe a -tzip %my_path%\apks_s\toalign%nome%.apk %my_path%\apks_d\%nome%\%%a.dex 

%my_path%\zipalign.exe -p -f 4 %my_path%\apks_s\toalign%nome%.apk %my_path%\apks_s\zipaligned%nome%.apk

del %my_path%\apks_s\toalign%nome%.apk

java -Xmx1024m -jar %my_path%\apksigner.jar sign --ks %my_path%\XXXX.jks --ks-pass pass:XXXXX --in %my_path%\apks_s\zipaligned%nome%.apk --out %my_path%\apks_s\signed%nome%.apk

del %my_path%\apks_s\zipaligned%nome%.apk
del %my_path%\apks_s\signed%nome%.apk.idsig

adb.exe install -r %my_path%\apks_s\signed%nome%.apk
```

**Comment by michelerenzullo** [comment]
UPDATE: 
- I just solved the issue with resources.arsc, adding it uncompressed as ZIP_STORE".
- Improved zipalign for new android versions, adding -p to ensure that they're aligned to a 4KiB page boundary suitable for mmap(2)
see my pull request and let me know.

Anyway, as the itsMoji and my version, your version has our same issue. when close the app and reopen it doesn't load anymore the pictures. There is some internal check to bypass, we should investigate on it
