### ISSUE TITLE
[HASH]

### ISSUE THREAD

**Issue by wendal2841** [Eltion/Instagram-SSL-Pinning-Bypass#22]
Hi, can you help me generate a query_hash for /api/v1/launcher/mobileconfig/ ?

SIGNATURE.{"bool_opt_policy":"0","mobileconfigsessionless":"","api_version":"3","unit_type":"1","query_hash":"dae17f1d3276207ebfe78f7a67cc9a04d4b88ff8c88dfc17e148fafb3f655b8e","device_id":"19ab534f-6663-4cf1-bc23-6b243c4db542","fetch_type":"ASYNC_FULL","family_device_id":"88E1F432-B994-45C1-A8CD-0BE4493E4004"}

**Comment by Eltion** [comment]
Hi @wendal2841, sorry but this is outside the scope of this repo!

**Comment by makovez** [comment]
HI @wendal2841, were you able to figure out how to generate query_hash ?
