### ISSUE TITLE
latest version

### ISSUE THREAD

**Issue by un9nplayer** [Eltion/Instagram-SSL-Pinning-Bypass#24]
need the latest version Frida js file. plzzz

**Comment by Eltion** [comment]
Is this not working for you https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/blob/main/instagram-ssl-pinning-bypass.js

**Comment by un9nplayer** [comment]
No application crash..!
the latest version out recently "262.0.0.24.327" 
its not working [Instagram-SSL-Pinning-Bypass](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/blob/main/instagram-ssl-pinning-bypass.js) on latest version.!

**Comment by Eltion** [comment]
@un9nplayer I can confirm that it's working on my phone. Can you post the the logcat when opening the application?
Also what architecture are you using?

**Comment by un9nplayer** [comment]
it worked.!!!
seems my noxplayer have some issue with HTTP/3 protocal.
thanks for confirming that it's working on your phone.!  it working perfectly.

**Comment by Eltion** [comment]
Thanks for confirming that. I'll close this issue.
