### ISSUE TITLE
[BUG] Can't capture request in Patched APK after closing the app

### ISSUE THREAD

**Issue by 2shiraz** [Eltion/Instagram-SSL-Pinning-Bypass#27]
**Describe the bug**  
Hi, I am facing a bug with the Pre Patched apk. When I launch the app for the first time with Burp capturing, Everything seems fine, But when I close the app (after login) and relaunch, the request capturing just stops. Although the app works fine but nothing is captured anymore. Restarting the emulator doesn't help but I'm able to recapture requests by clearing data or reinstalling the app.

**Method**  
Patched APK

**App info**
 - Version: instagram-v265.0.0.19.301-x86_64
 - Arch: x86_64

**Device info**
- Model: Samsung SM-G9810, Nox Emulator
- Android Version: 9

**Proxy tool**
brup: v2022.12.6

**Comment by Eltion** [comment]
@2shiraz this is because the instagram is using HTTP/3. There is already an issue for this here https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/issues/19

A temporary solution for this is to delete the config file that instagram creates, I've added a function for this but it's commented for now, to enable it just uncomment this line and patch the apk:
```patch
- //disableHTTP3();
+ disableHTTP3();
```

**Comment by Eltion** [comment]
I just patched a version you can test which should disable HTTP/3
https://send.vis.ee/download/dbfb59f4eadf5b46/#vTI2ZmIXZcQqBB8w4JtfgQ

**Comment by Taz03** [comment]
@Eltion the link expired can u make a new one?

**Comment by 2shiraz** [comment]
Here
https://www.mediafire.com/file/rlwlltmj7lyimu1/instagram-v265.0.0.19.301-x86_64+(1).apk/file

**Comment by 2shiraz** [comment]
> @Eltion the link expired can u make a new one?
Here
https://www.mediafire.com/file/rlwlltmj7lyimu1/instagram-v265.0.0.19.301-x86_64+(1).apk/file

**Comment by Taz03** [comment]
@2shiraz thanks :heart: it is working now

**Comment by abdullahsaeed98** [comment]
> https://send.vis.ee/download/dbfb59f4eadf5b46/#vTI2ZmIXZcQqBB8w4JtfgQ

can you make a patch for arm8v-64 version?
