### ISSUE TITLE
Client TLS handshake failed.

### ISSUE THREAD

**Issue by Mistes974** [Eltion/Instagram-SSL-Pinning-Bypass#30]
**Describe the bug**  

I can't get it to work. In my terminal i get :
`Client TLS handshake failed. The client does not trust the proxy's certificate for infinitedata-pa.googleapis.com (OpenSSL Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]))`

While if I open the Chrome browser I can see the different requests with mitmproxy, and for that I installed the mitmproxy certificate. But in the patched app i only get this error, with tcp unusable informations.
 (I tried with and without mitmproxy certificate and instagram patched app and it didnt work :/ )

**Method**  
Patched APK

**App info**
instagram-v265.0.0.19.301-arm64-v8a.apk

**Device info**
- Model: Pixel 4 , android studio emulator 
- Android Version: 12

**Proxy tool**
mitmproxy: v9.0.1

**Comment by Eltion** [comment]
@Mistes974, the error is for the domain `infinitedata-pa.googleapis.com`. This script will bypass SSL pinning for `*.instagram.com`.
If you're not able to see any requests made at `*.instagram.com`, then It probably means that the app is using HTTP/3 and that will skip the proxy.  
 
To disable to HTTP/3 check these issues:
https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/issues/19
https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/issues/27
