### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ncek-XD** [Eltion/Instagram-SSL-Pinning-Bypass#33]
**Describe the bug**  

**Method**  
Patched APK or Frida

**App info**
 - Version: instagram-v248.0.0.17.109
 - Arch: x86, x86_64, armeabi-v7a, arm64-v8a

**Device info**
- Model: Samsung SM-A525F, Nox Emulator
- Android Version: 12

**Proxy tool**
mitmproxy: v8.1.1
brup: v2022.5.2

**Logs**
Frida or logcat logs, screenshots, mitmproxy event logs, Brup event log.

**Additional context**

**Comment by Eltion** [comment]
@ncek-XD  can you give more context what the problem is?

**Comment by Eltion** [comment]
Latest version: https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/releases/tag/v275.0.0.27.98

**Comment by Adam-meta** [comment]
Ter bagi file crak ige donk

**Comment by Adam-meta** [comment]
Ter bli file crak ig open sourkut brp
