### ISSUE TITLE
instagram keeps stopping

### ISSUE THREAD

**Issue by trxyazilimedu** [Eltion/Instagram-SSL-Pinning-Bypass#36]
I modded my own app but it keeps crashing

App info

Version: instagram-v273.0.0.14.72
Arch: arm64-v8a

Device info

Model: Samsung SM-G950F
Android Version: 9

![image](https://user-images.githubusercontent.com/82735255/223000782-5631e6be-8159-400a-9133-2af24533b5c7.png)

**Comment by Eltion** [comment]
[Duplicate]
Follow the discussion on this issue: https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/issues/37
Latest version: https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/issues/37

**Comment by trxyazilimedu** [comment]
> Hi thanks for the reply I used bypass with frida instead it still works smoothly even in the latest version
