### ISSUE TITLE
[BUG] Instagram crashes right after start with patched APK

### ISSUE THREAD

**Issue by maddo7** [Eltion/Instagram-SSL-Pinning-Bypass#37]
**Describe the bug**  
Instagram crashes right after start

**Method**  
Patched APK with your python patcher

**App info**
 - Version: instagram-v274.0.0.26.90
 - Arch: arm64-v8a

**Device info**
- Model: Samsung A53
- Android Version: 13

**Proxy tool**

brup: v2023.2.3

**Logs**
logcat logs attached
[logcat.log](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/files/11017278/logcat.log)f

**Additional context**
The patched APK crashes right after start. The files from your repo work without issues.
Here is the stock apk (base.apk) from Google Play and the patched one.
https://drive.google.com/file/d/1VcSC7KZgS4HkGV6AL5_iUj04yXJmkN1m/view?usp=share_link

Any help to get this working is highly appreciated.

**Comment by Eltion** [comment]
Seems like instagram has started to use packed relocations for the native libs and that's causing this problem.
![image](https://user-images.githubusercontent.com/18504798/228093768-1ca61603-03d2-46ce-a294-47a34147b69e.png)

Currently the [lief-project](https://github.com/lief-project/LIEF) which I'm using to patch the native so file does not support this. There is a branch with some implementation of this feature here: [android-packed-relocations](https://github.com/lief-project/LIEF/tree/android-packed-relocations).

I was able to manually do that and you can check the latest version here:
https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/releases/tag/v275.0.0.27.98

**Comment by evgen-dev** [comment]
Can you release version 278+ ? Thanks.

**Comment by GamerGirlandCo** [comment]
> Seems like instagram has started to use packed relocations for the native libs and that's causing this problem. ![image](https://user-images.githubusercontent.com/18504798/228093768-1ca61603-03d2-46ce-a294-47a34147b69e.png)
> 
> Currently the [lief-project](https://github.com/lief-project/LIEF) which I'm using to patch the native so file does not support this. There is a branch with some implementation of this feature here: [android-packed-relocations](https://github.com/lief-project/LIEF/tree/android-packed-relocations).
> 
> I was able to manually do that and you can check the latest version here: https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/releases/tag/v275.0.0.27.98

do you mind sharing the process of manually patching..?

**Comment by Eltion** [comment]
I will try and see maybe I can can do a pull request to lief project which will fix this issue.

**Comment by maddo7** [comment]
Thank you very much for your efforts.
Did I understand correctly that the Frida script still works with the newest version, just the patching has some issues?

**Comment by evgen-dev** [comment]
Frida still work with latest versions

**Comment by Eltion** [comment]
Updated the patch script on the lateset version
