### ISSUE TITLE
[BUG] Process terminated

### ISSUE THREAD

**Issue by davdu31** [Eltion/Instagram-SSL-Pinning-Bypass#39]
**Describe the bug**  
While I start frida, the android app start but frida crash. The app don't crash on the device.
`frida -U -l ~/instagram-ssl-pinning-bypass.js -f com.instagram.android`

After, in mitmproxy, the TCP connection are still encrypted while I copy the mitmproxy certifica in /system/etc/security/cacerts/..

**Method**  
Frida with the patched apk of the repo

**App info**
 - Version: instagram-v265.0.0.19.301-x86_64
 - Arch:  x86_64

**Device info**
- Model: google pixel emulate vie avd : "system-images;android-30;google_apis;x86_64"
- Android Version: 11

**Proxy tool**
mitmproxy: v9.0.1

**Logs**
![Capture d’écran_2023-05-07_19-10-47](https://user-images.githubusercontent.com/35230152/236692269-3884e090-b96b-447c-959a-5e05741fc5ff.png)

**Comment by Eltion** [comment]
This is probably a problem with firda and emulator, maybe try a different emulator
