### ISSUE TITLE
Pictures doesn't load anymore after closing the app first time

### ISSUE THREAD

**Issue by michelerenzullo** [Eltion/Instagram-SSL-Pinning-Bypass#4]
As itsMoji and my version Instagram introduced in the last 3 months something to check ssl unpinning, when opening the app the first time everything works good with the proxy, but when you close it and reopen it doesn't work anymore and doesn't load any picture. We  should investigate maybe on smali source code. I will take a look

An idea would be to find the first version with this new security check and do diffing, but is a bit stressing I guess and will take a while, but is the only one that I have rn.

**Comment by Eltion** [comment]
I'm unable to replicate this problem.
Tested in Nox Emulator and Android Emulator(Android R)
ABI: x86
App version [instagram-v240.2.0.18.107-x86.apk](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/releases/download/v240.2.0.18.107/instagram-v240.2.0.18.107-x86.apk)
Using mitmproxy to capture the the traffic.

Can you tell me what environment you are using?

**Comment by michelerenzullo** [comment]
Last version you suggested in the README.md, I downloaded from there, I tested both ABI: arm and arm64 , Android 12, Google Pixel 6, using Burp, I will test later the x86 on AVD emulator, it seems I'm not the only one.

Can you publish the new release with the fix for Android R+? So we make sure to verify exactly the same version.

I just login the first time and it works, but if I close and I open with the proxy setted it doesn't load anymore, I have to disable the proxy

**Comment by Eltion** [comment]
I've updated the release https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/releases/tag/v240.2.0.18.107 with the fix.

**Comment by Eltion** [comment]
I was able to replicate the problem you mention using Brup v1.7. By any chance are you using Brup v1.x.x?

**Comment by michelerenzullo** [comment]
I am using Burp 1.6.2, you were able to replicate it because of Burp? Or with mitmproxy doesn't appear?

**Comment by Eltion** [comment]
Yes. I think it's not working with Brup v1. It works with the latest version of brup.
Error message from brup: `The client failed to negotiate an SSL connection to i.instagram.com:443: no cipher suites in common`

**Comment by michelerenzullo** [comment]
I configrm, solved.

- On Burp v1.6.2 Project options - TLS Negotiation there is TLSv1.3 but it doesn't seem to work, therefore I tried to enable the feature in Internal - "Whitehat" settings of Instagram "Do not use TLSv1.3" and it works even with v1.6.2 . 

- I update to the new version of Burp 2022.5.2 and the support for TLS v1.3 seems to work fine even without disabling it in Instagram. I guess they fixed something internally in Burp with new version

**Comment by pizzaso** [comment]
@michelerenzullo 

I have an issue open [here](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/issues/6), I was trying to run the standalone frida script to bypass the ssl pinning using ```frida -H 172.20.10.11 -f com.instagram.android -l trace.js --no-pause```, but it didn't work for me (i have a rooted pixel 4) and i'm not sure why, I thought it was a certificate or proxy problem but I tried patching the apk this morning (reading what the patch does, I think it bundles the bypass script and the frida gadget into the apk which doesn't require root) and that worked so I don't think it was related to that and I'm still no sure what the problem is.
