### ISSUE TITLE
[BUG] Does not Work

### ISSUE THREAD

**Issue by Hammad69275** [Eltion/Instagram-SSL-Pinning-Bypass#41]
**Describe the bug**  
I have installed the patch apk but burp is still showing this unknown_ca error.

**Method**  
Patched APK

**App info**
 - Version: instagram-v256.0.0.18.105
 - Arch: armeabi-v7a

**Device info**
- Model: Infinix X657B
- Android Version:  13
- Lineage OS  GSI

**Proxy tool**
burp: v2023.6.2.0

**Logs**
![image](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/assets/72254541/251cde36-cbf7-47df-b57b-b0e3d5ec7b42)

**Additional context**
My phone is a rooted infinix with lineage os 20 gsi running. I have tried using burp without installing the ca certificate, installing it as a user certificate and also installing it as a system certificate but none of these methods have worked for me.

**Comment by Scylla2020** [comment]
I've tried both the apk and the frida script and nothing works. Instagram login gets stuck on loading. Maybe its some new pinning technique because I see many other videos where chrome works with burp but is completely failing now

**Comment by Eltion** [comment]
Can you show the logs from the script, it's working for me .
![image](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/assets/18504798/812cbd5b-05e7-4edb-980f-ed9de55a95ca)

**Comment by Scylla2020** [comment]
> Can you show the logs from the script, it's working for me .
> 
> ![image](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/assets/18504798/812cbd5b-05e7-4edb-980f-ed9de55a95ca)
> 
> 

Does it keep working as you continue clicking around after logging in, viewing followers, doing search etc? For me sometimes it seemed to print some calls before login then afterwards always nothing registers

**Comment by Eltion** [comment]
That is because the application is using HTTP/3. There is an issue about this and a workaround. 
Check this issue: https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/issues/19

**Comment by Hammad69275** [comment]
Can you try running the patched apk on an actual device? it still doesnt work for me and all it prints is that it failed to negotiate tls connection due to bad certificate in burp

**Comment by Pugn0** [comment]
Hello, I'm starting in this world of research, could you guide me where I can find quality content like the one I'm reading.

Areas I'm willing to explore and gain knowledge are APK reverse engineering, network protocol interception and vulnerability analysis.

In advance, I thank everyone involved.
