### ISSUE TITLE
[BUG] Patched apk doesn't open

### ISSUE THREAD

**Issue by Taz03** [Eltion/Instagram-SSL-Pinning-Bypass#46]
I followed the [Patch  APK](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass#patch-apk) guide but when I installed the app on my phone it installs successfully but doesn't open. But when I installed an already patched version it works fine.

**App info**
 - Version: instagram-v293.0.2.28.93
 - Arch: arm64-v8a

**Device info**
- Model: Realme Narzo 50A
- Android Version: 13

![2023-07-27_21-51](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/assets/73871477/6da20ba0-0f2f-4a9a-9edf-e0bcdfc2c211)

**Comment by levikap** [comment]
I'm also getting this error.
App version: Instagram 296.0.0.35.109 
Arch: arm64-v8a

Device model: Pixel 6
Android version: 12

**Comment by 350d** [comment]
Anyone have any progress with patching? 302.xxx version crashed for me too.

**Comment by dilame** [comment]
Same thing here

**Comment by readak** [comment]
You're having a problem with Frida.If you try it manually, there is no crash problem. (I mean **frida -U -l instagram-ssl-pinning-bypass.js -f com.instagram.android**)

**Comment by dilame** [comment]
Thank's for answer, @readak 
I tried `.js` version too. The app successfully opens, but network requests fails. "Could not refresh feed" or something.
Could you please share the info, what you do next, after unpinning with `instagram-ssl-pinning-bypass.js` ? Is it mitmproxy? Is there something special?

**Comment by dilame** [comment]
Just now I was able to manually patch `libliger.so`.
I can confirm it works on my setup:
```
Apple M1 Pro chip
Genymotion with Android 11
Instagram 307.0.0.34.111
Mitmproxy
```
 I appreciate this community, so i'm sharing it here.
[libliger.so.zip](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/files/13256374/libliger.so.zip)

**Comment by q1179336367** [comment]
> libliger

I use the same version of ins as you, and I also use the so package you sent, but I still can't catch the package. I am android 9, x86_64, could you please tell me the reason?

**Comment by dilame** [comment]
@q1179336367 as i mentioned, i am on `Apple M1 Pro chip` that means `arm64` architecture.
