### ISSUE TITLE
instagram lite

### ISSUE THREAD

**Issue by tiastiof** [Eltion/Instagram-SSL-Pinning-Bypass#47]
This bypass does not work on Instagram Lite

**Comment by Eltion** [comment]
This repo is not for instagram lite. It's possible to bypass also instagram lite but the protocol they use is a variation of MQTT and not HTTP, so you would need to parse it.

**Comment by niraularohan** [comment]
> This repo is not for instagram lite. It's possible to bypass also instagram lite but the protocol they use is a variation of MQTT and not HTTP, so you would need to parse it.

Can you be specific? Do you know of any way to do this? I am trying to do this, but I am not getting quite there, can you help me here?
