### ISSUE TITLE
Last commit broken the previous fix for Android R+

### ISSUE THREAD

**Issue by michelerenzullo** [Eltion/Instagram-SSL-Pinning-Bypass#5]
[Commit](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/commit/9b417e8b0797c4b3ff5a53f8798244794ced3565)

line 172, 174, 175 has to be reverted, we fixed the issue but later you deleted this code and broken the building:

```
[...] and not file.filename.startswith("resources.arsc"):
    [...]
if not os.path.exists(os.path.join(TEMP_FOLDER, file.filename)) and file.filename.startswith("resources.arsc"):
    apk_out.writestr(file.filename, apk_in.read(file.filename), compress_type=zipfile.ZIP_STORED, compresslevel=0)
```

resources.arsc has to be STORED not COMPRESSED, otherwise it doesn't build a valid apk file on R

**Comment by Eltion** [comment]
Can you check my comment on the pull request: https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/pull/3.
My idea was that for each file we will copy the compression method for the original apk. So if in the original apk the compression for resources.arsc is STORED it will be STORED also in the patched apk.

**Comment by michelerenzullo** [comment]
I cannot find your comment in the pull request?

Well I like that, this is the same idea that I used in my script, but as is written now it doesn't work.

You wanna do that? I think you have to copy and paste a duplicate of the original APK and update the archive overwriting the few patched files / inserting new files, without editing anything else, in this case I'm sure it will work because it works good for me since years without updating, I never encountered this bug.

I will show you how I would do that later.

**Comment by Eltion** [comment]
Can you help me test if the [release](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/releases/tag/v240.2.0.18.107) form README.md is working for you?

**Comment by michelerenzullo** [comment]
Yes, the [release](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/releases/tag/v240.2.0.18.107) works, but the question is did you create it **without** or **with** the line about resources.arsc? Because when I run the script without that line it doesn't install
Could you double check? Thanks

**Comment by Eltion** [comment]
It's without the line. I think what is happening is that you're trying to patch an apk file where the resources.arsc is already compressed. You can try to install the apk without patching and if I'm correct it should not work.

![image](https://user-images.githubusercontent.com/18504798/175780259-57850176-44e8-400e-9a02-7edf0c9ec393.png)
In the picture above you can see that  resources.arsc  the method is STORE. It should be like this before and after patching.

**Comment by Eltion** [comment]
Sorry maybe I was a bit confusing. What I'm asking is that you maybe can check the original APK file if resources.arsc is compressed or just stored. If it is compressed then it won't work with the change that I did.

**Comment by michelerenzullo** [comment]
Ok, sorry for the waste of time, basically I thought, for mistake, that the link in the README.md was to the **"original"/"unpatched"** version and I was using the previous one (the broken one that you removed, zipped with Deflate) as input for patch_apk.py, so the output was Deflated as well. I download the original apk from a mirror and it works fine. I close

![Immagine 2022-06-25 174419](https://user-images.githubusercontent.com/76132686/175780943-2e040546-bbd6-4105-8929-026ca7ce3c68.png)

**Comment by michelerenzullo** [comment]
> Sorry maybe I was a bit confusing. What I'm asking is that you maybe can check the original APK file if resources.arsc is compressed or just stored. If it is compressed then it won't work with the change that I did.

Yeah because you built the release the 22nd June, before the commit of 23rd June about "file.compress_type" and "apk_in.infolist()", I was using this version of 22nd June, patching an already patched apk(such a dumb).

The real solution was file.compress_type and was already on your repository.

**Comment by Eltion** [comment]
No problem this was actually my fault I forgot to submit my review of your pull request where I explained why I switched it back. Thanks for all the help :)
