### ISSUE TITLE
[BUG] ZAProxy shows no requests logs using Frida SSL bypass script on Instagram v320

### ISSUE THREAD

**Issue by RigDillinger** [Eltion/Instagram-SSL-Pinning-Bypass#59]
**Describe the bug**  
Bypass script does not work on new Instagram release `320-0-0-42-101`
No logs come from Instagram app to ZAProxy. Logging in to Instagram is not successful either.
See screenshots.

**Method** 
Frida

**App info**
 - Version: instagram-v320-0-0-42-101
 - Arch: tested on: `x86, x86_64, arm64-v8a`

**Device info**
- Model: Pixel 6 Pro, Android Studio Emulator
- Android Version: `9 arm64 API 28`, `10 x86 API 29`, `11 x86_64 API 34`, no Google services

**Proxy tool**
ZAProxy 2.14.0

**Logs**
![Screenshot_2024-02-29_142901_edit](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/assets/10511882/308b1367-26c4-4691-873b-f14da01cc12d)

![Screenshot_2024-02-29_142830](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/assets/10511882/a3f9eace-0bf1-4faf-9e20-7137cb62c656)

![Screenshot_2024-02-29_142932_edit](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/assets/10511882/d940fca9-cd4f-4ba5-baa4-d66b9277af27)

**Additional context**
I attempted a simple debug:
![Screenshot_2024-02-29_143520](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/assets/10511882/146446f4-0c4a-4fdc-bae4-2047a1866676)

I can see these logs just fine on Instagram v319 as well as requests in ZAProxy and able to log in to Instagram successfully.
Please, have a look.

**Comment by trxyazilimedu** [comment]
![image](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/assets/82735255/87c61708-8d40-40c3-bc62-f16d61c70b38)
![image](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/assets/82735255/8944ec7d-07b4-4987-bf07-f4b8d2b345f7)
I use Samsung Galaxy A50 and Burp suite, I have the same error.

**Comment by evgen-dev** [comment]
For some reason, the application goes online without going through a proxy

**Comment by evgen-dev** [comment]
For me works https://github.com/httptoolkit/frida-interception-and-unpinning/. But first you need to add proxygen ssl verification interception (method _ZN8proxygen15SSLVerification17v... in libliger.so) to native-tls-hook.js. And add mitm (or the proxy you use) cert to config.js file.

**Comment by MaksZ25** [comment]
Can you please provide or help with this? Tried to add to native-tls-hook.js but haven't progress

**Comment by evgen-dev** [comment]
> @evgen-dev Can you please provide or help with this? Tried to add to native-tls-hook.js but haven't progress

Created a fork and made the necessary changes. And create pull request.

**Comment by MaksZ25** [comment]
> Hi @MaksZ25 Created a fork and made the necessary changes. And create pull request. https://github.com/evgen-dev/frida-interception-and-unpinning

Oh. I Just tried same code too but without progess. Will check tonight again. Can you please provide your tg username?

**Comment by evgen-dev** [comment]
> > Hi @MaksZ25 Created a fork and made the necessary changes. And create pull request. https://github.com/evgen-dev/frida-interception-and-unpinning
> 
> Oh. I Just tried same code too but without progess. Will check tonight again. Can you please provide your tg username?

This code still works for me. But works only cold start (clear all app data and then launch app)

**Comment by evgen-dev** [comment]
@ultrafragile Have you replaced these values ​​with yours?
![Monosnap frida-interception-and-unpinning_config j](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/assets/10253845/6b6e2010-523f-4ece-be16-5458d3b3c4ed)

**Comment by MaksZ25** [comment]
@evgen-dev Not works anymore. In debug I see unix:stream connections ignoring.

`   . . . .   Connected to Pixel 3 (id=127.0.0.1:6555)
Spawning `com.instagram.android`...                                     

*** Starting scripts ***

*** Java available *** version = undefined
== Redirecting all TCP connections to 192.168.88.252:9999 ==
[+] Patched 2 libssl.so verification methods
== Hooked native TLS lib libssl.so ==
Spawned `com.instagram.android`. Resuming main thread!
[Pixel 3::com.instagram.android ]-> Ignoring unix:dgram connection                       
OnEnter: args: /system/framework/oat/x86/org.apache.http.legacy.odex                     
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: org.apache.http.legacy.odex
OnEnter: args: /data/app/~~956t7k1iyRw55TWN5k-4bQ==/com.instagram.android-6Gxki74QXADf0OXvoz2PXA==/oat/x86/base.odex
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: base.odex                                             
== Proxy system configuration overridden to 192.168.88.252:9999 ==
Rewriting <class: android.net.PacProxySelector>
Rewriting <class: java.net.ProxySelector>
Rewriting <class: sun.net.spi.DefaultProxySelector>
== Proxy configuration overridden to 192.168.88.252:9999 ==
[+] Injected cert into com.android.org.conscrypt.TrustedCertificateIndex
[ ] Skipped cert injection for org.conscrypt.TrustedCertificateIndex (not present)
[ ] Skipped cert injection for org.apache.harmony.xnet.provider.jsse.TrustedCertificateIndex (not present)
== System certificate trust injected ==

    === Disabling all recognized unpinning libraries ===
[+] javax.net.ssl.HttpsURLConnection setDefaultHostnameVerifier
[+] javax.net.ssl.HttpsURLConnection setSSLSocketFactory
[+] javax.net.ssl.HttpsURLConnection setHostnameVerifier
[+] javax.net.ssl.SSLContext init(KeyManager;[], TrustManager;[], SecureRandom)
[ ] com.android.org.conscrypt.CertPinManager isChainValid
[+] com.android.org.conscrypt.CertPinManager checkChainPinning
[+] android.security.net.config.NetworkSecurityConfig $init(*) (0)
[+] android.security.net.config.NetworkSecurityConfig $init(*) (1)
[+] com.android.okhttp.internal.tls.OkHostnameVerifier verify(String, SSLSession)
[+] com.android.okhttp.Address $init(String, int, Dns, SocketFactory, SSLSocketFactory, HostnameVerifier, CertificatePinner, Authenticator, Proxy, List, List, Pr
oxySelector)
[ ] com.android.okhttp.Address $init(String, int, SocketFactory, SSLSocketFactory, HostnameVerifier, CertificatePinner, Authenticator, Proxy, List, List, ProxySe
lector)
[ ] okhttp3.CertificatePinner *
[ ] com.squareup.okhttp.CertificatePinner *
[ ] com.datatheorem.android.trustkit.pinning.PinningTrustManager *
[ ] appcelerator.https.PinningTrustManager *
[ ] nl.xservices.plugins.sslCertificateChecker *
[ ] com.worklight.wlclient.api.WLClient *
[ ] com.worklight.wlclient.certificatepinning.HostNameVerifierWithCertificatePinning *
[ ] com.worklight.androidgap.plugin.WLCertificatePinningPlugin *
[ ] com.commonsware.cwac.netsecurity.conscrypt.CertPinManager *
[ ] io.netty.handler.ssl.util.FingerprintTrustManagerFactory *
[ ] com.silkimen.cordovahttp.CordovaServerTrust *
[ ] com.appmattus.certificatetransparency.internal.verifier.CertificateTransparencyHostnameVerifier *
[ ] com.appmattus.certificatetransparency.internal.verifier.CertificateTransparencyInterceptor *
[ ] com.appmattus.certificatetransparency.internal.verifier.CertificateTransparencyTrustManager *
== Certificate unpinning completed ==
== Unpinning fallback auto-patcher installed ==
*** Scripts completed ***

Ignoring attempt to override http.proxyHost system property
Ignoring attempt to override https.proxyHost system property
Ignoring attempt to override http.proxyPort system property
Ignoring attempt to override https.proxyPort system property
Ignoring attempt to override http.nonProxyHosts system property
Ignoring attempt to override https.nonProxyHosts system property
 => android.security.net.config.NetworkSecurityConfig $init(*) (0)
 => android.security.net.config.NetworkSecurityConfig $init(*) (0)
 => android.security.net.config.NetworkSecurityConfig $init(*) (0)
 => android.security.net.config.NetworkSecurityConfig $init(*) (0)
 => android.security.net.config.NetworkSecurityConfig $init(*) (0)
 => android.security.net.config.NetworkSecurityConfig $init(*) (0)
OnEnter: args: /data/app/~~956t7k1iyRw55TWN5k-4bQ==/com.instagram.android-6Gxki74QXADf0OXvoz2PXA==/lib/x86/libsuperpack-jni.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libsuperpack-jni.so
OnEnter: args: /data/app/~~956t7k1iyRw55TWN5k-4bQ==/com.instagram.android-6Gxki74QXADf0OXvoz2PXA==/lib/x86/libbreakpad.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libbreakpad.so
OnEnter: args: /data/app/~~956t7k1iyRw55TWN5k-4bQ==/com.instagram.android-6Gxki74QXADf0OXvoz2PXA==/lib/x86/libfb.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libfb.so
OnEnter: args: /data/app/~~956t7k1iyRw55TWN5k-4bQ==/com.instagram.android-6Gxki74QXADf0OXvoz2PXA==/lib/x86/libc++_shared.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libc++_shared.so
OnEnter: args: /data/app/~~956t7k1iyRw55TWN5k-4bQ==/com.instagram.android-6Gxki74QXADf0OXvoz2PXA==/lib/x86/libfbjni.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libfbjni.so
OnEnter: args: /data/app/~~956t7k1iyRw55TWN5k-4bQ==/com.instagram.android-6Gxki74QXADf0OXvoz2PXA==/lib/x86/liblinkerutils.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: liblinkerutils.so
OnEnter: args: /data/app/~~956t7k1iyRw55TWN5k-4bQ==/com.instagram.android-6Gxki74QXADf0OXvoz2PXA==/lib/x86/libdistract.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libdistract.so
OnEnter: args: /data/app/~~956t7k1iyRw55TWN5k-4bQ==/com.instagram.android-6Gxki74QXADf0OXvoz2PXA==/lib/x86/libsigmux.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libsigmux.so
OnEnter: args: /data/app/~~956t7k1iyRw55TWN5k-4bQ==/com.instagram.android-6Gxki74QXADf0OXvoz2PXA==/lib/x86/libandroid_aware_dlopen.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libandroid_aware_dlopen.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libredexsharedmerged.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libredexsharedmerged.so
OnEnter: args: /data/app/~~956t7k1iyRw55TWN5k-4bQ==/com.instagram.android-6Gxki74QXADf0OXvoz2PXA==/lib/x86/libmemalign16.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libmemalign16.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libdextricksmerged.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libdextricksmerged.so
OnEnter: args: /data/app/~~956t7k1iyRw55TWN5k-4bQ==/com.instagram.android-6Gxki74QXADf0OXvoz2PXA==/lib/x86/libelf.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libelf.so
OnEnter: args: /data/app/~~956t7k1iyRw55TWN5k-4bQ==/com.instagram.android-6Gxki74QXADf0OXvoz2PXA==/lib/x86/libfb_xzdecoder.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libfb_xzdecoder.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libloommerged_1.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libloommerged_1.so
OnEnter: args: /data/app/~~956t7k1iyRw55TWN5k-4bQ==/com.instagram.android-6Gxki74QXADf0OXvoz2PXA==/lib/x86/libfbunwindstack.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libfbunwindstack.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libloommerged.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libloommerged.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libpthread_interceptor.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libpthread_interceptor.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libappstatelogger2.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libappstatelogger2.so
OnEnter: args: libdl.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libdl.so
OnEnter: args: libc.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libc.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libhiddenapis2.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libhiddenapis2.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libfbdomains.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libfbdomains.so
OnEnter: args: /data/app/~~956t7k1iyRw55TWN5k-4bQ==/com.instagram.android-6Gxki74QXADf0OXvoz2PXA==/lib/x86/libfbsofterror.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libfbsofterror.so
OnEnter: args: /data/app/~~956t7k1iyRw55TWN5k-4bQ==/com.instagram.android-6Gxki74QXADf0OXvoz2PXA==/lib/x86/libglog.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libglog.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libliger-common.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libliger-common.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libmobilenetworkstack.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libmobilenetworkstack.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/librealtime.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: librealtime.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libmobileconfig.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libmobileconfig.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/lib_bandwidth_estimator.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: lib_bandwidth_estimator.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libbandwidth_estimator_jni.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libbandwidth_estimator_jni.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libtigon.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libtigon.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libliger.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libliger.so
[+] Hooked function: _ZN8proxygen15SSLVerification17verifyWithMetricsEbP17x509_store_ctx_stRKNSt6__ndk112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEP
NS0_31SSLFailureVerificationCallbacksEPNS0_31SSLSuccessVerificationCallbacksERKNS_15TimeUtilGenericINS3_6chrono12steady_clockEEERNS_10TraceEventE
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libfbaudiomerged.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libfbaudiomerged.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libtigonligerlite-jni.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libtigonligerlite-jni.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/librtc.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: librtc.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libmsysxplatmerged.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libmsysxplatmerged.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libmediapipeline.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libmediapipeline.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libardelivery-merged.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libardelivery-merged.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libIGL.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libIGL.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libarfxgraphicsmerged.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libarfxgraphicsmerged.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libxplat_perflogger_xanalytics_xanalyticsAndroid.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libxplat_perflogger_xanalytics_xanalyticsAndroid.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libperfloggerxplat_init.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libperfloggerxplat_init.so
OnEnter: args: libc.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libc.so
OnEnter: args: libart.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libart.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libaddressspace.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libaddressspace.so
Manually intercepting connection to [2a:3:28:80:f2:45:0:ca:fa:ce:b0:c:0:0:43:fe]:443
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libmediapipeline-iglu-merged.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libmediapipeline-iglu-merged.so
Ignoring unix:stream connection
Ignoring unix:stream connection
Connected tcp6 fd 94 to null (-1)
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libaborthooks.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libaborthooks.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libstrings.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libstrings.so
OnEnter: args: libart.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libart.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libunwindstack_stream.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libunwindstack_stream.so
OnEnter: args: /data/app/~~956t7k1iyRw55TWN5k-4bQ==/com.instagram.android-6Gxki74QXADf0OXvoz2PXA==/lib/x86/libbreakpad_cpp_helper.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libbreakpad_cpp_helper.so
OnEnter: args: libbreakpad_cpp_helper.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libbreakpad_cpp_helper.so
OnEnter: args: libart.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libart.so
OnEnter: args: libc++.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libc++.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libdistractutil.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libdistractutil.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libsigquit.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libsigquit.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libnightwatch.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libnightwatch.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libfbnightwatch.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libfbnightwatch.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libnative_memdump.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libnative_memdump.so
OnEnter: args: libandroid.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libandroid.so
OnEnter: args: /vendor/lib/egl/libEGL_emulation.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libEGL_emulation.so
OnEnter: args: /vendor/lib/egl/libGLESv1_CM_emulation.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libGLESv1_CM_emulation.so
OnEnter: args: /vendor/lib/egl/libGLESv2_emulation.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libGLESv2_emulation.so
 => javax.net.ssl.SSLContext init(KeyManager;[], TrustManager;[], SecureRandom)
OnEnter: args: libart.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libart.so
OnEnter: args: /system/lib/libEGL.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libEGL.so
OnEnter: args: /system/lib/libGLESv1_CM.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libGLESv1_CM.so
OnEnter: args: /system/lib/libGLESv2.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libGLESv2.so
 => com.android.okhttp.Address $init(String, int, Dns, SocketFactory, SSLSocketFactory, HostnameVerifier, CertificatePinner, Authenticator, Proxy, List, List, Pr
oxySelector)
Ignoring unix:stream connection
Ignoring unix:stream connection
Connected tcp6 fd 89 to {"ip":"::ffff:192.168.88.252","port":9999} (-1)
 => com.android.okhttp.internal.tls.OkHostnameVerifier verify(String, SSLSession)
OnEnter: args: /vendor/lib/egl/libGLESv1_CM_emulation.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libGLESv1_CM_emulation.so
OnEnter: args: /vendor/lib/egl/libGLESv2_emulation.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libGLESv2_emulation.so
Ignoring unix:stream connection
OnEnter: args: /vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: android.hardware.graphics.mapper@2.0-impl.so
OnEnter: args: /vendor/lib/hw/gralloc.ranchu.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: gralloc.ranchu.so
Ignoring unix:stream connection
OnEnter: args: libandroid.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libandroid.so
 => javax.net.ssl.SSLContext init(KeyManager;[], TrustManager;[], SecureRandom)
 => com.android.okhttp.Address $init(String, int, Dns, SocketFactory, SSLSocketFactory, HostnameVerifier, CertificatePinner, Authenticator, Proxy, List, List, Pr
oxySelector)
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libminscompiler-jni.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libminscompiler-jni.so
Ignoring unix:stream connection
Ignoring unix:stream connection
Connected tcp6 fd 148 to {"ip":"::ffff:192.168.88.252","port":9999} (-1)
 => com.android.okhttp.internal.tls.OkHostnameVerifier verify(String, SSLSession)
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libflexlayout.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libflexlayout.so
Manually intercepting connection to [2a:3:28:80:f0:45:0:10:fa:ce:b0:c:0:0:0:3]:443
Ignoring unix:stream connection
Ignoring unix:stream connection
Connected tcp6 fd 159 to {"ip":"::ffff:192.168.88.252","port":9999} (-1)
Manually intercepting connection to [2a:3:28:80:f0:45:0:10:fa:ce:b0:c:0:0:0:3]:443
Ignoring unix:stream connection
Ignoring unix:stream connection
Connected tcp6 fd 160 to {"ip":"::ffff:192.168.88.252","port":9999} (-1)
Manually intercepting connection to [2a:3:28:80:f0:45:0:10:fa:ce:b0:c:0:0:0:3]:443
Ignoring unix:stream connection
Ignoring unix:stream connection
Connected tcp6 fd 161 to {"ip":"::ffff:192.168.88.252","port":9999} (-1)
Manually intercepting connection to [2a:3:28:80:f0:45:0:10:fa:ce:b0:c:0:0:0:3]:443
Ignoring unix:stream connection
Ignoring unix:stream connection
Connected tcp6 fd 162 to null (-1)
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libcryptopub.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libcryptopub.so
OnEnter: args: /data/data/com.instagram.android/lib-compressed/libcryptopub-jni.so
OnLeave - MODULE_LOAD_CALLBACKS: [object Object], moduleName: libcryptopub-jni.so
`

**Comment by birinet-copliot** [comment]
It works unpinning without any problem for me.

![aaa](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/assets/111762906/050776f9-b059-4076-a315-fbd3aaaba51e)

**Comment by shadowc0de** [comment]
> @ultrafragile Have you replaced these values ​​with yours? ![Monosnap frida-interception-and-unpinning_config j](https://private-user-images.githubusercontent.com/10253845/317846148-6b6e2010-523f-4ece-be16-5458d3b3c4ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzY0MzgsIm5iZiI6MTcxMjQ3NjEzOCwicGF0aCI6Ii8xMDI1Mzg0NS8zMTc4NDYxNDgtNmI2ZTIwMTAtNTIzZi00ZWNlLWJlMTYtNTQ1OGQzYjNjNGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA3NDg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZmY5ZDQ3YWIxY2NiZmI3OWFmMzMxM2I3YjI3NWM0YmMyNGEzODgzYzI2YWFlNWEzNDAyNzFhZmQyMTU2OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1y_wtepMxzZT-Ga0DWTOP8vscBBIF9qSe91DiZRMs0M)


![image](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/assets/29227416/ff62e5a4-fd62-4adb-9487-dc23dcd671d7)
May I know what command you used? It still doesn’t capture any request, anyone?

**Comment by mdc-git** [comment]
@evgen-dev 

Thank you for your efforts. It works a bit for me. I can scroll through my profile page fine, but the search doesn't work and clicking on other profiles doesn't work either.
I'm getting messages like this in frida shell:

```
 !!! --- Unexpected TLS failure --- !!!
      SSLPeerUnverifiedException: java.security.cert.CertificateException: Didn't find a trust anchor in chain cleanup!
      Thrown by X.176->A00
      [ ] Unrecognized TLS error - this must be patched manually

 !!! --- Unexpected TLS failure --- !!!
      CertificateException: Didn't find a trust anchor in chain cleanup!
      Thrown by X.0Mg->A00
      [ ] Unrecognized TLS error - this must be patched manually
```

Everytime I use the non working parts, mitmproxy tells me:  `the client doesn't trust the proxy's certificate` for `gateway.instagram.com` and `edge-mqtt.facebook.com`. It catches the requests from `i.instagram.com`, though.

Command I used:

```
frida -U \
    -l ./config.js \
    -l ./native-connect-hook.js \
    -l ./native-tls-hook.js \
    -l ./android/android-proxy-override.js \
    -l ./android/android-system-certificate-injection.js \
    -l ./android/android-certificate-unpinning.js \
    -l ./android/android-certificate-unpinning-fallback.js \
    -f com.instagram.android
```

**Comment by MaksZ25** [comment]
@evgen-dev Write me on tg please: alx_grx
