### ISSUE TITLE
Issue getting frida script to work

### ISSUE THREAD

**Issue by pizzaso** [Eltion/Instagram-SSL-Pinning-Bypass#6]
I tried using the frida script to bypass the pinning on my phone (arm64-v8a ABI) but it didn't work, i am still getting certificate errors for some reason?

Can you help me with this?

**Comment by Eltion** [comment]
Of course. Can you tell me the following?
Which instagram version are you using?
Can you show me the log of the script after running frida?
Which tool are you using to capture the trafic?

Also could you try the patched apk if it's working for you?

**Comment by pizzaso** [comment]
@Eltion,

Thank you for the quick reply,

The app version is **241.1.0.18.114**, for frida i'm running the script and the two functions are hooked (i can see the verify one called when opening the app) but the certificate errors are still there, and i've tried using both mitmproxy and burp but to no avail.

I prefer running the gadget instead of the patched apk as the versions change quickly buy if i can't solve this i guess there is not other way then.

**Comment by Eltion** [comment]
@pizzaso 

Do you see requests form `i.instagram.com` or no requests at all?

**Comment by pizzaso** [comment]
No, no requests at all

**Comment by pizzaso** [comment]
@Eltion 
This

Burp (certificate unknown):

![image](https://user-images.githubusercontent.com/108372243/176317464-dbacecd8-05ae-4b14-8297-ba4ee5b004fa.png)

mitmproxy:

![image](https://user-images.githubusercontent.com/108372243/176317891-70950dea-11f4-4a6c-8165-7b2dd066390f.png)

Rarely do i see an error for **i.instagram.com** (also saw [this](https://forum.search-guard.com/t/ssl-problem-insufficient-buffer-remaining-for-aead-cipher-fragment-in-elaticsearch/1891) error a few times before , and that's when i bumped my java version from 8 to 16 and also tried mitmproxy)

No sure the above is helpful, these domains suggest that they speak MQTT and i know that's not what we are patching for but mayge it could help.

**Comment by Eltion** [comment]
Yes your correct. Actually we are only patching for the instagram api requests. A lot of the others are patched using the build in android CertificateFactory. To do that you can use https://codeshare.frida.re/@pcipolloni/universal-android-ssl-pinning-bypass-with-frida/. But I would expect that `i.instagra.com` requests to be captured.

**Comment by pizzaso** [comment]
@Eltion 

Tried with burp (after navigating a lot of screens) and saw this:

![image](https://user-images.githubusercontent.com/108372243/176320004-f276f055-65e2-4412-9042-e6155ee07e17.png)

(this is when i decided to use mitmproxy)

For mitmproxy it just gives a certificate no trusted sslv3 error, think it's a generic error.

**Comment by pizzaso** [comment]
@Eltion 

This is for Burp (after navigating a lot of screens):

![image](https://user-images.githubusercontent.com/108372243/176320120-d960de48-241e-4a62-8fa9-a0022d4c14e5.png)

this is when i decided to use mitmproxy, for the latter, it just gives a generic "certificate not trusted" error.

**Comment by pizzaso** [comment]
@Eltion Yes ,i am using the up to date version 2022.5.2

**Comment by Eltion** [comment]
It looks this is a openJDK problem as you mentioned https://bugs.openjdk.org/browse/JDK-8221218. Can you run `java --version` and check java version.

For me its:

`openjdk 17.0.3 2022-04-19                                                                                                 
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)                                                           
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing) `

**Comment by pizzaso** [comment]
@Eltion 

This is the output:
```powershell
>java -version
openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7)
OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (build 16.0.2+7, mixed mode, sharing)
```

I was using java 8 and updated because of the error above to version16 but no luck, I'll try reinstalling Burp maybe it'll help although i have little hope.

**Comment by Eltion** [comment]
Can you also update Java from here https://adoptium.net/

**Comment by pizzaso** [comment]
No luck 😥 

```powershell
>java -version
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)

#Tried to launch the jar directly instead of the windows executable

>java -jar -Xmx4g burpsuite_community_v2022.5.2.jar
Your JRE appears to be version 17.0.3 from Eclipse Adoptium
Burp has not been fully tested on this platform and you may experience problems.
Built new session factory
```

**Comment by pizzaso** [comment]
@Eltion,

The patched apk worked fine but the frida script didn't, not sure what that means 😕  ??

**Comment by pizzaso** [comment]
@Eltion,

At least i know it's not a problem with the certificate or the proxy

**Comment by pizzaso** [comment]
@Eltion 

I just reviewed the script, it's doing the same thing apart that it bundles the frida script and the frida gadget inside the app essentially assuming that you'll work with a non-rooted phone.

I have a rooted phone so it should'nt be a problem for me running the bypass directly, hmm not sure what's happening?

**Comment by Eltion** [comment]
@pizzaso 
Yes that's all it does. That's really strange problem. I just tested with x86 and frida it's working. 

frida-server version : 15.1.22

Unfortunately I can't test for arm.

**Comment by pizzaso** [comment]
Consider this resolved
