### ISSUE TITLE
[BUG] Erro when start

### ISSUE THREAD

**Issue by fellipgomes** [Eltion/Instagram-SSL-Pinning-Bypass#60]
**Describe the bug**  
When i execute the script, showing error 

frida -U -l instagram-ssl-pinning-bypass.js -f com.instagram.android

   . . . .   Connected to SM G991B (id=RQCR60062ZK)
Spawning `com.instagram.android`...                                     
[*][*] Waiting for libliger...
Spawned `com.instagram.android`. Resuming main thread!                  
[SM G991B::com.instagram.android ]-> [*][+] Hooked checkTrustedRecursive
[*][+] Hooked SSLContextInit
[*][+] Found libliger at: 0x7a6f9bb000
[*][+] Hooked function: _ZN8proxygen15SSLVerification17verifyWithMetricsEbP17x509_store_ctx_stRKNSt6__ndk112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEPNS0_31SSLFailureVerificationCallbacksEPNS0_31SSLSuccessVerificationCallbacksERKNS_15TimeUtilGenericINS3_6chrono12steady_clockEEERNS_10TraceEventE
Process terminated
[SM G991B::com.instagram.android ]->

Thank you for using Frida!

**Method**  
Frida

**App info**
 - Version: instagram-v275.0.0.27.98-arm64-v8a.apk

**Device info**
- Model: Samsung SM G991B
- Android Version: 12

**Proxy tool**
Burp

**Logs**

[*][+] Hooked function: _ZN8proxygen15SSLVerification17verifyWithMetricsEbP17x509_store_ctx_stRKNSt6__ndk112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEPNS0_31SSLFailureVerificationCallbacksEPNS0_31SSLSuccessVerificationCallbacksERKNS_15TimeUtilGenericINS3_6chrono12steady_clockEEERNS_10TraceEventE
Process terminated
[SM G991B::com.instagram.android ]->

Thank you for using Frida!

**Additional context**

**Comment by evgen-dev** [comment]
If you are using the patched version from this repo (instagram-v275.0.0.27.98-arm64-v8a), why are you using frida?
Patched apps should work without frida.

**Comment by pamanbobb** [comment]
> If you are using the patched version from this repo (instagram-v275.0.0.27.98-arm64-v8a), why are you using frida? Patched apps should work without frida.

using frida mean we can see the instagram traffic even with latest instagram apps. that it's !

**Comment by evgen-dev** [comment]
> using frida mean we can see the instagram traffic even with latest instagram apps. that it's !


Yes, captain!
