### ISSUE TITLE
Not working on Recent versions of Instagram app (Version 330) - Maybe Update Needed

### ISSUE THREAD

**Issue by amir-alikhani** [Eltion/Instagram-SSL-Pinning-Bypass#61]
I had a successful patching apk instagram version 314 by the python script.  It works great. :)
But when i try to patch instagram version 330, although the script run successfully and apk patched file generated, but executing the patched instagram app,  causes an unexpected closing after trying to open the instagram app.!!!

I tried on instagram version 330 and 331 both the patched instagram app closed unexpectedly after execution.

can any one help me how to investigate this issue,!!??
maybe an update needed on script on newer version of instagram...

thank you in advance...

**Comment by amir-alikhani** [comment]
no idea?!!

**Comment by lanbda1** [comment]
I have fixed version 314 of Instagram, but it keeps crashing. Can you send me your fixed version of Instagram 314?
