### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by cemiritireng** [Eltion/Instagram-SSL-Pinning-Bypass#65]
can you help me solve this problem?
python3 patch_apk.py -i Instagram_354.2.0.47.100_APKPure.apk -o Instgrm.apk
App ABIs:  ['arm64-v8a']
Supported ABIs:  ['arm64-v8a']
Generating keystore...
Generating 2,048 bit RSA key pair and self-signed certificate (SHA256withRSA) with a validity of 8,000 days
        for: CN=com.leftenter.android, OU=ID, O=APK, L=Unknown, ST=Unknown, C=XK
[Storing /home/firman404/Instagram-SSL-Pinning-Bypass/temp/release.keystore]
Created config_file at:  /home/firman404/Instagram-SSL-Pinning-Bypass/temp/libgadget.config.so
Created script_file at:  /home/firman404/Instagram-SSL-Pinning-Bypass/temp/libsslbypass.js.so

Patching for arm64-v8a
Downloading firda-gadget-16.5.6-arm64-v8a.so.xz
[==================================================]

Traceback (most recent call last):
  File "/home/firman404/Instagram-SSL-Pinning-Bypass/patch_apk.py", line 263, in <module>
    main()
  File "/home/firman404/Instagram-SSL-Pinning-Bypass/patch_apk.py", line 251, in main
    download_frida_gadget(arch)
  File "/home/firman404/Instagram-SSL-Pinning-Bypass/patch_apk.py", line 163, in download_frida_gadget
    return extract_frida_gadget(archive_path, arch)
  File "/home/firman404/Instagram-SSL-Pinning-Bypass/patch_apk.py", line 139, in extract_frida_gadget
    with open(filepath, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/firman404/Instagram-SSL-Pinning-Bypass/temp/lib/arm64-v8a/libgadget.so'
@Eltion

**Comment by Eltion** [comment]
Fixed on the new version
