### ISSUE TITLE
[GUIDE] Instruction how to fix 352+ Failed to hook function: _ZN8proxygen15SSLVerification

### ISSUE THREAD

**Issue by expectedfailure** [Eltion/Instagram-SSL-Pinning-Bypass#67]
Instagram merely updated the library version, and that changed the name of the function a bit.
It was
`_ZN8proxygen15SSLVerification17verifyWithMetricsEbP17x509_store_ctx_stRKNSt6__ndk112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEPNS0_31SSLFailureVerificationCallbacksEPNS0_31SSLSuccessVerificationCallbacksERKNS_15TimeUtilGenericINS3_6chrono12steady_clockEEERNS_10TraceEventE`
now it's
`_ZN8proxygen15SSLVerification17verifyWithMetricsEbP17x509_store_ctx_stRKNSt6__ndk212basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEPNS0_31SSLFailureVerificationCallbacksEPNS0_31SSLSuccessVerificationCallbacksERKNS_15TimeUtilGenericINS3_6chrono12steady_clockEEERNS_10TraceEventE`

Just update the func name in the script and everything will work as before.
Have a nice day =)

ps
Stop selling this, you idiots. It took a few minutes to find the new function, it's literally in the same place, have a conscience

**Comment by EarsKilla** [comment]
also `libliger.so` -> `libliger-common.so` or am i wrong?

but still can't mitm v354 using fiddler :c

**Comment by Eltion** [comment]
Should be fixed with: https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/commit/7035aaed48db7f75ea906e8ba9909d42aa2980b1

Thanks @expectedfailure @EarsKilla

**Comment by soorooghadim** [comment]
> Should be fixed with: [7035aae](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/commit/7035aaed48db7f75ea906e8ba9909d42aa2980b1)
> 
> Thanks @expectedfailure @EarsKilla
Please Update patch_apk.py

**Comment by ribollae** [comment]
Doesn't work for 356+ versions.

**Comment by pamanbobb** [comment]
![image](https://github.com/user-attachments/assets/cec797da-9a53-410c-9c86-bc870c776879)
There was issue again on threads where using latest version.

**Comment by firaki12345-cmd** [comment]
> Doesn't work for 356+ versions.

hi how did you patch versions above 336 ?
