### ISSUE TITLE
another question about real phone

### ISSUE THREAD

**Issue by caixinminnihao** [Eltion/Instagram-SSL-Pinning-Bypass#7]
Hello, I have a doubt, because I am not using an emulator, it is a real machine, I can't go over the wall, how to use mitmproxy to capture packets.
if you know, please guide me, thank you very much.

**Comment by Eltion** [comment]
Hi @caixinminnihao. It should be the same steps as with an emulator. I created an tutorial video which you can follow. I hope it helps 😃

https://user-images.githubusercontent.com/18504798/177385493-5fd557bd-cb59-4342-b6d8-8b70262e6c06.mp4

e
