### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '///*/inst/new_bypass_prof/temp/lib/arm64-v8a/libgadget.so'

### ISSUE THREAD

**Issue by bb-cmd** [Eltion/Instagram-SSL-Pinning-Bypass#71]
App ABIs:  ['arm64-v8a']
Supported ABIs:  ['arm64-v8a']
Generating keystore...
Generating 2 048 bit RSA key pair and self-signed certificate (SHA256withRSA) with a validity of 8 000 days
  for: CN=com.leftenter.android, OU=ID, O=APK, L=Unknown, ST=Unknown, C=XK
[Storing /home/tapesmile/revers/inst/new_bypass_prof/temp/release.keystore]
Created config_file at:  /*/*/*/inst/new_bypass_prof/temp/libgadget.config.so
Created script_file at:  /*/*/*/inst/new_bypass_prof/temp/libsslbypass.js.so

Patching for arm64-v8a
Downloading firda-gadget-16.5.6-arm64-v8a.so.xz
[==================================================]

Traceback (most recent call last):
  File "patch_apk.py", line 267, in <module>
    main()
  File "patch_apk.py", line 255, in main
    download_frida_gadget(arch, frida_version)
  File "patch_apk.py", line 165, in download_frida_gadget
    return extract_frida_gadget(archive_path, arch)
  File "patch_apk.py", line 139, in extract_frida_gadget
    with open(filepath, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/*/*/*/inst/new_bypass_prof/temp/lib/arm64-v8a/libgadget.so'

I used instagram ver.357. But for vet.333 still working. 
After decomp. 357 apk, i cant find  libgadget.so files and other. 
![photo_2024-11-13_18-37-26](https://github.com/user-attachments/assets/44078156-e938-472a-95cb-918170ad5616)

But in 333 version this files are present. Have any idia how to fix it?

**Comment by tapesmile** [comment]
In latest version instagram app, absent this libs: ["libmemalign16.so","libfb.so"]. Еhis is why the error occurs. @Eltion Hi. Do you fix it any time?

**Comment by firaki12345-cmd** [comment]
> I suppose the app generates those files after installation.

hi is there any fix for this yet ? 

thanks

**Comment by Eltion** [comment]
Should be fixed in the last update
