### ISSUE TITLE
help

### ISSUE THREAD

**Issue by sulycat** [Eltion/Instagram-SSL-Pinning-Bypass#73]
can you please help me i dont get all the traffic or apis 
like i dont get the /v1/login i get the bloks one instead and a lot of them 
and also and i also dont get this api when i change the username to get the traffic of it https://i.instagram.com/api/v1/bloks/apps/com.bloks.www.fxim.settings.username.change.async/

can someone help or atleast give me this one ? any help appreciated thanks
using memu , burpsuite

**Comment by sulycat** [comment]
im using memu and burp suite

**Comment by sulycat** [comment]
isnt it like filtering to see which one contains bloks? on it or api 
 or the specified word ? and send it to the repeater to see? 
 or i dont understand 
 sorry for bothering you @erenctnky

**Comment by Eltion** [comment]
Closing this since it's outside repo domain
