### ISSUE TITLE
[BUG] Instagram 361.0.0.46.88 rooted SSL unpin script no longer works

### ISSUE THREAD

**Issue by VendorAttestation** [Eltion/Instagram-SSL-Pinning-Bypass#79]
**Describe the bug**  
Instagram 361.0.0.46.88 no longer unpins

**Method**  
Frida

**App info**
 - Version: Instagram 361.0.0.46.88
 - Arch:  arm64-v8a

**Device info**
- Model: Pixel 5
- Android Version: 14

**Proxy tool**
mitmproxy v11.0.2

**Logs**
None it just doesn't hook that unpin context class

**Comment by firaki12345-cmd** [comment]
hi so which version works best for you ?

for me works best is 

[https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-336-0-0-35-90-release/instagram-336-0-0-35-90-43-android-apk-download/](url)

**Comment by evgen-dev** [comment]
Now libliger*.so renamed to **libstartup.so** in app (this lib contain method ...verifyWithMetrics....)
But simply replacing the library name does not solve the problem with version 361

**Comment by firaki12345-cmd** [comment]
> Now libliger*.so renamed to **libstartup.so** in app (this lib contain method ...verifyWithMetrics....)
> But simply replacing the library name does not solve the problem with version 361

What does that method do ? Maybe you have to inject it with Frida and return something with it. I guess.

**Comment by Eltion** [comment]
I've updated the script for the new versions
