### ISSUE TITLE
Can you make the patched apk for the Tiktok ?

### ISSUE THREAD

**Issue by abdullahsaeed98** [Eltion/Instagram-SSL-Pinning-Bypass#8]
Tiktok ssl pinning can already bypass in rooted android phone/emulator. But I need the pached Apk to run on non rooted phone.
https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/tik-tok-including-musical-ly-25-4-4-release/

**Comment by abdullahsaeed98** [comment]
@Eltion

**Comment by Eltion** [comment]
Hi @abdullahsaeed98. I'll look into this soon. How do you bypass it in the emulator? That could help me find a solution. Thanks.

**Comment by abdullahsaeed98** [comment]
@Eltion I use this xposed module in emulator. enabling this bypass the pinning.
https://github.com/ac-pm/SSLUnpinning_Xposed

**Comment by abdullahsaeed98** [comment]
It seems to only patched the okhttp.
If you can create patched apk for latest tiktok version of available abis it will be great.

Do let us know the procedure of patching so we can patch upcoming verisons.

**Comment by abdullahsaeed98** [comment]
@Eltion were you able to look into it?

**Comment by Eltion** [comment]
Hi @abdullahsaeed98 .
 Sorry for the late response. I had a change to look into this today. And I think this is possible. I'll soon share with you my findings.

**Comment by abdullahsaeed98** [comment]
Thanks for the update. Just for the remiander the latest version currently is 25.9.4.

**Comment by Eltion** [comment]
@abdullahsaeed98  just created a repo for this
https://github.com/Eltion/Tiktok-SSL-Pinning-Bypass

**Comment by abdullahsaeed98** [comment]
@Eltion Thanks alot.
