### ISSUE TITLE
[GUIDE] Working very Well on Version 360 

### ISSUE THREAD

**Issue by firaki12345-cmd** [Eltion/Instagram-SSL-Pinning-Bypass#81]
**Very simple to make it work, No need to even patch the apk**

**Steps Below**

1. First Download the Appropriate Version of instagram from apkmirror (Depending on your Device Architecture), i got mine from below

[https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-360-0-0-52-192-release/](url)

2. Install it on your device

3. log into instagram 

4. now make a **insta_bypass.js** file on your machine and open it with VSCODE and paste the following code from below website.

[https://codeshare.frida.re/@Eltion/instagram-ssl-pinning-bypass/](url)

5. Now remove the **const functionName** and paste the new one from below and save the file.

**Thanks to @expectedfailure  for the below FIX**

`const functionName = "_ZN8proxygen15SSLVerification17verifyWithMetricsEbP17x509_store_ctx_stRKNSt6__ndk212basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEPNS0_31SSLFailureVerificationCallbacksEPNS0_31SSLSuccessVerificationCallbacksERKNS_15TimeUtilGenericINS3_6chrono12steady_clockEEERNS_10TraceEventE";`

7. and finally now connect your device, using adb and paste the following command. (Make sure your instagram is running)

You will see the function gets hooked and everything works, I use mitmproxy and am getting all the details fine.

`frida --device dce1e347 -N com.instagram.android -l insta_bypass.js` **(Your Device name or number will be different)**
```
     ____
    / _  |   Frida 16.5.7 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to AC2001 (id=dce1e347)
[*][*] Waiting for libliger...
[*][+] Hooked checkTrustedRecursive
[*][+] Hooked SSLContextInit
[AC2001::com.instagram.android ]-> [*][+] Found libliger at: 0x6eed1d4000
[*][+] Hooked function: _ZN8proxygen15SSLVerification17verifyWithMetricsEbP17x509_store_ctx_stRKNSt6__ndk212basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEPNS0_31SSLFailureVerificationCallbacksEPNS0_31SSLSuccessVerificationCallbacksERKNS_15TimeUtilGenericINS3_6chrono12steady_clockEEERNS_10TraceEventE
```

**Comment by comboed** [comment]
thank you!

**Comment by comboed** [comment]
![image](https://github.com/user-attachments/assets/8141701d-124f-4dcd-b085-5304e92e18ca)
The script can't seem to locate the new function

**Comment by firaki12345-cmd** [comment]
> ![image](https://github.com/user-attachments/assets/8141701d-124f-4dcd-b085-5304e92e18ca)
> The script can't seem to locate the new function

Hi did you replace the const functionName with new one above ?

And make sure your version of Instagram is 360 and NOT 361 (according to your architecture)

And then wipe data AND CACHE of your instagram
Open app
Log in again (make sure you are using normal wifi or mobile data without proxy enabled)

And keep the app running 

Now ON the proxy 

And then run the Frida script. (Hopefully shall work)

Because mine stopped working. So i just cleaned the instagram app data and cache and logged in again normally and then worked.

Thanks

**Comment by comboed** [comment]
Still not working even with provided steps. Snooped in the APK and did not seem to find "libliger.so" I'm assuming it does not get loaded at all

**Comment by firaki12345-cmd** [comment]
> Still not working even with provided steps. Snooped in the APK and did not seem to find "libliger.so" I'm assuming it does not get loaded at all

maybe try it on your device instead of emulator ?

**Comment by comboed** [comment]
Performed same thing, still nothing. 

> > Still not working even with provided steps. Snooped in the APK and did not seem to find "libliger.so" I'm assuming it does not get loaded at all
> 
> maybe try it on your device instead of emulator ?

Don't have a device to test with unfortunately. Might have to take the lost on this one.

**Comment by timelis** [comment]
With your help we were able to get it working, thank you!

**Comment by firaki12345-cmd** [comment]
> With your help we were able to get it working, thank you!

If you can get this working on latest version.. let us know as well.

Thanks.

**Comment by timelis** [comment]
I am in the process of learning about frida and would like to try this problem as I learn!

**Comment by fghooost** [comment]
Hello, does anyone have a solution for 361?

**Comment by evgen-dev** [comment]
Now libliger*.so renamed to libstartup.so in app (this lib contain method ...verifyWithMetrics....)
But simply replacing the library name does not solve the problem with version 361

**Comment by Eltion** [comment]
I've released a new version which should work: https://github.com/Eltion/Instagram-SSL-Pinning-Bypass
