### ISSUE TITLE
I am having issues with the requests.

### ISSUE THREAD

**Issue by vxphuongictu** [Eltion/Instagram-SSL-Pinning-Bypass#82]
Hello, I would like to ask how to log the request headers using instagram-ssl-pinning-bypass.js? I am trying to hook a new method to listen for request headers, specifically I want to search for the Authorization header without using a MITM proxy. Can someone help me with this?

**Comment by vxphuongictu** [comment]
The version I am currently using is: https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-336-0-0-35-90-release/instagram-336-0-0-35-90-43-android-apk-download/

**Comment by Eltion** [comment]
Try using the new version
