### ISSUE TITLE
[BUG] Account settings does not working

### ISSUE THREAD

**Issue by cadmax** [Eltion/Instagram-SSL-Pinning-Bypass#83]
**Bug**  
Running the version [instagram-v361.0.0.46.88-arm64-v8a.apk](https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/releases/download/v361.0.0.46.88/instagram-v361.0.0.46.88-arm64-v8a.apk) with MuMu Android emulator, the account settings on app does not working well.

- Path
Home -> Profile pic -> Hamburguer icon -> result

![image](https://github.com/user-attachments/assets/67513b1a-a9e1-4917-ae24-ecb4d05a74e6)

**Comment by evgen-dev** [comment]
Followes/following list doesn't work either. Looks like there is a problem with intercepting requests to graphql

**Comment by Eltion** [comment]
Should be fixed with the PR from @evgen-dev:
https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/pull/92
