### ISSUE TITLE
Commands to create patch apk on macOs?

### ISSUE THREAD

**Issue by rdxshubham** [Eltion/Instagram-SSL-Pinning-Bypass#9]
Hey, 

Can you help me with similar commands for macOS as you have posted in the readme for Ubuntu?

**Comment by Eltion** [comment]
Hi @rdxshubham, to make the script work you will need to install java on your mac. You can then get **apksigner** and **zipalign** from here https://dl.google.com/android/repository/build-tools_r30.0.1-macosx.zip.

Note that apksigner and zipalign should be added to the PATH env variable so the script works. 
Unfortunalty I can't test it on a mac but it should work.
